---
services:
  jenkins:
    image: {Your_Repo}/jenkins-sdp:latest
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-sdp
    volumes:
      - jenkinsHome:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

volumes:
    jenkinsHome:
      driver: local

...
